

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBlock;
                ref class Button;
                ref class Grid;
            }
        }
    }
}
namespace VungleSDK {
    namespace UI {
        ref class VungleAdControl;
    }
}

namespace CPP_sample_WP8_1
{
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::TextBlock^ appIDTextBlock;
        private: ::Windows::UI::Xaml::Controls::Button^ InitSDK;
        private: ::Windows::UI::Xaml::Controls::Grid^ ButtonsPanel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ placement1TextBlock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ placement1IDTextBlock;
        private: ::Windows::UI::Xaml::Controls::Button^ PlayPlacement1;
        private: ::VungleSDK::UI::VungleAdControl^ embeddedControl;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ placement2TextBlock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ placement2IDTextBlock;
        private: ::Windows::UI::Xaml::Controls::Button^ PlayPlacement2;
        private: ::Windows::UI::Xaml::Controls::Button^ LoadPlacement2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ placement3TextBlock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ placement3IDTextBlock;
        private: ::Windows::UI::Xaml::Controls::Button^ PlayPlacement3;
        private: ::Windows::UI::Xaml::Controls::Button^ LoadPlacement3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ cachedTextBlock;
    };
}

